server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL-AUTO:UPDATE}

jwt:
  signerKey: ${JWT_SIGNERKEY}
  valid-duration: ${JWT_VALID-DURATION:36000} #seconds
  refreshable-duration: ${JWT_REFRESHABLE-DURATION:360000} #seconds
